package dev.androidgui.core.designsystem.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Color values ported from LibChecker md_themes.xml, Apache-2.0.
// Copyright the LibChecker contributors. Snapshot: 7ea356187e89652f486c60608560ffee628992b3.
// Modified for Compose: explicit ColorScheme roles, surface tint, and fixed palette roles.
internal val FixedLightColorScheme: ColorScheme = lightColorScheme(
    primary = Color(0xFF6D23F8),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFEADDFF),
    onPrimaryContainer = Color(0xFF21005E),
    inversePrimary = Color(0xFFD0BCFF),
    secondary = Color(0xFF615B70),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE8DFF8),
    onSecondaryContainer = Color(0xFF1E192B),
    tertiary = Color(0xFF7D5260),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFD8E4),
    onTertiaryContainer = Color(0xFF31101D),
    background = Color(0xFFFFFBFE),
    onBackground = Color(0xFF1C1B1E),
    surface = Color(0xFFFFFBFE),
    onSurface = Color(0xFF1C1B1E),
    surfaceVariant = Color(0xFFE6E1E6),
    onSurfaceVariant = Color(0xFF484649),
    surfaceTint = Color(0xFF6D23F8),
    inverseSurface = Color(0xFF313033),
    inverseOnSurface = Color(0xFFF4EFF3),
    error = Color(0xFFBA1B1B),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD4),
    onErrorContainer = Color(0xFF410001),
    outline = Color(0xFF79767A),
    outlineVariant = Color(0xFFCAC5CA),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFFFBFE),
    surfaceDim = Color(0xFFE0DAE2),
    surfaceContainer = Color(0xFFF3EDF7),
    surfaceContainerHigh = Color(0xFFECE6F0),
    surfaceContainerHighest = Color(0xFFE6E1E6),
    surfaceContainerLow = Color(0xFFF7F2FA),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    primaryFixed = Color(0xFFEADDFF),
    primaryFixedDim = Color(0xFFD0BCFF),
    onPrimaryFixed = Color(0xFF21005E),
    onPrimaryFixedVariant = Color(0xFF5200CE),
    secondaryFixed = Color(0xFFE8DFF8),
    secondaryFixedDim = Color(0xFFCBC2DC),
    onSecondaryFixed = Color(0xFF1E192B),
    onSecondaryFixedVariant = Color(0xFF4A4458),
    tertiaryFixed = Color(0xFFFFD8E4),
    tertiaryFixedDim = Color(0xFFEFB7C8),
    onTertiaryFixed = Color(0xFF31101D),
    onTertiaryFixedVariant = Color(0xFF633B48),
)

internal val FixedDarkColorScheme: ColorScheme = darkColorScheme(
    primary = Color(0xFFD0BCFF),
    onPrimary = Color(0xFF380094),
    primaryContainer = Color(0xFF5200CE),
    onPrimaryContainer = Color(0xFFEADDFF),
    inversePrimary = Color(0xFF6D23F8),
    secondary = Color(0xFFCBC2DC),
    onSecondary = Color(0xFF332D41),
    secondaryContainer = Color(0xFF4A4458),
    onSecondaryContainer = Color(0xFFE8DFF8),
    tertiary = Color(0xFFEFB7C8),
    onTertiary = Color(0xFF492532),
    tertiaryContainer = Color(0xFF633B48),
    onTertiaryContainer = Color(0xFFFFD8E4),
    background = Color(0xFF1C1B1E),
    onBackground = Color(0xFFE6E1E6),
    surface = Color(0xFF1C1B1E),
    onSurface = Color(0xFFCAC5CA),
    surfaceVariant = Color(0xFF484649),
    onSurfaceVariant = Color(0xFFCAC5CA),
    surfaceTint = Color(0xFFD0BCFF),
    inverseSurface = Color(0xFFE6E1E6),
    inverseOnSurface = Color(0xFF605D62),
    error = Color(0xFFFFB4A9),
    onError = Color(0xFF680003),
    errorContainer = Color(0xFF930006),
    onErrorContainer = Color(0xFFFFDAD4),
    outline = Color(0xFF938F94),
    outlineVariant = Color(0xFF484649),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF3B383E),
    surfaceDim = Color(0xFF141218),
    surfaceContainer = Color(0xFF211F26),
    surfaceContainerHigh = Color(0xFF2B2930),
    surfaceContainerHighest = Color(0xFF36343B),
    surfaceContainerLow = Color(0xFF1D1B20),
    surfaceContainerLowest = Color(0xFF0F0D13),
    primaryFixed = Color(0xFFEADDFF),
    primaryFixedDim = Color(0xFFD0BCFF),
    onPrimaryFixed = Color(0xFF21005E),
    onPrimaryFixedVariant = Color(0xFF5200CE),
    secondaryFixed = Color(0xFFE8DFF8),
    secondaryFixedDim = Color(0xFFCBC2DC),
    onSecondaryFixed = Color(0xFF1E192B),
    onSecondaryFixedVariant = Color(0xFF4A4458),
    tertiaryFixed = Color(0xFFFFD8E4),
    tertiaryFixedDim = Color(0xFFEFB7C8),
    onTertiaryFixed = Color(0xFF31101D),
    onTertiaryFixedVariant = Color(0xFF633B48),
)
